### ISSUE TITLE
Reestablish the digitization simulation in Fatras

### ISSUE THREAD

**Issue by msmk0** [acts-project/acts#139]
Digitization functionality exists currently as a `Core` plugin. Since it is simulation functionality it belongs to the Fatras component.

* [x] Add generic container for hierarchical geometry information #120
* [ ] Add segmentation information data structure (based on #120)
* [ ] Add resolution information data structure (based on #120)
* [ ] Define and implement the configuration file format #138
* [ ] Add digitized hit event data type
* [x] Add Gaussian-smearing hit digitization
* [ ] Add Geometry hit digitization

Depends on #138.

**Comment by msmk0** [comment]
Work is ongoing.

**Comment by paulgessinger** [comment]
Is this addressed, @asalzburger ?

**Comment by gagnonlg** [comment]
I think #663 mostly takes care of this. The configuration format and algorithm (DigitizationAlgorithm) allows to do everything asked for in the checklist, so we can close this one.
