### ISSUE TITLE
Fatras for the OpenDataDetector

### ISSUE THREAD

**Issue by msmk0** [acts-project/acts#159]
This is a tracking issue for Fatras-related issues that need to be resolved to have a working simulation of the OpenDataDetector:

* [ ] (Re-)establish configurable digitization support #139
* [ ] Introduce support to simulate electro-magnetic conversions #189 
* [ ] (optional) Add support for point-like physics interactions #194 
* [ ] (optional) Introduce minimal support for nuclear interactions

**Comment by asalzburger** [comment]
This is being worked on. #388 will address a lot of this.
