### ISSUE TITLE
Tracking for TPC/DC without surfaces 

### ISSUE THREAD

**Issue by FabianKlimpel** [acts-project/acts#165]
Using a TPC/DC for measuring trajectories of charged particles is related to a setup in which the detecting element is located at a different position than the origin of the measurement. Hence the scenario is different to e.g. modules in a tracking detector. A current method for tracking in TPC/DC relies on the construction of surfaces for each measurement at its origin such that the Kalman filter formalism can be applied. However this involves the construction/destruction of many surfaces as well as coordinate transformations of the particle's parametrisation for each surface. In order to avoid this workload, further development is required to allow track reconstruction without surface dependencies for TPCs/DCs.
The therefore required steps can be grouped as:
1. Measurement description
- [ ]  Free measurement description
Our current measurements are restricted to a bound parametrisation. In order to handle a free measurement, appropriate adaptions are required
- [ ]  Event storage
As the measurements need modifications the same would account to the storage of their collection.
- [ ] Calibrator
A calibrator for the measurements is required that locates the measurements including corrections like space charge distortions.
2. Track extrapolation
- [ ] Propagation needs to handle FreeParameters
The current Propagator and stepper classes can only handle bound parametrisation. This concept needs to be extended such that FreeParameters can be used.
- [ ] Actor to stop propagation at right position
An actor is required to stop the propagation at a given position for applying the Kalman filter formalism.
3. Track finding & fitting
- [ ]  Kalman filter for free parameters
The current Kalman filter is able to handle only bound parametrisations and must be extended therefore by FreeParameters.
- [ ]  TrackState
The current TrackState stores bound parametrisations and jacobians from bound to bound parametrisations. When FreeParameters should become possible, the dimensions are not fixed anymore.
- [ ] CKF
Similar to the Kalman filter the CKF needs to learn when and how to act.

**Comment by FabianKlimpel** [comment]
After having a brief look into creating a measurement with free parameters and an associated volume instead of a surface showed that multiple smaller sub-steps are necessary:

- [ ] For a measurement in `FreeParameters` we will need the possibility to project certain dimensions out from out parameters. Alongside with some other function calls that occur on a `ParameterSet` for bound parametrisations make an analogue formalism necessary. This will become the `FreeParameterSet`.

- [ ] Implementing the `FreeParameterSet` allows to modify the corresponding parts in the `SingleFreeParameters` such that its structure will become similar to the bound parametrisations.

- [ ] The current measurement only stores surfaces. In order to make the same available for volumes, a different class is required like a `FreeMeasurement`

**Comment by HadrienG2** [comment]
Blocked on EDM rework and Stepper rework.
