### ISSUE TITLE
Workpackage: Geometry

### ISSUE THREAD

**Issue by asalzburger** [acts-project/acts#185]
This is the epic description of the geometry streamlining and cleanup.

**Cleanup and Bugfixes:**
- [x] #73 harmonise the orientation of boundary surfaces (cleanup), PR: #196
   - the idea of PR is to reduce the complexity of the boundary surface orientation, inside/outside as concepts are replaced by along/opposite w.r.t normal vector
- [ ] #166 fix polyhedron description for sectoral bounds (bugfix)
  - at least the visualisation of sectoral bounds (cylindrical/conical) could be flawed
- [x] #186 refactor the surface parsing module (improvement)
  - this PR promotes a new class `ProtoLayerHelper` that receives a list of surfaces and sorts them into `ProtoLayer` objects, PR: #212 
 - the `ProtoLayer` objects can then be used to build `LayerArray` objects or later Volume structures
- [x] Remove `TAKE_SMALLER_BIGGER` macros (improvement), PR: #206
- [ ] Check and fix `noexcept(false)` usage for constructors
- [ ] Deprecate `distanceToBoundary(...)` infrastructure, PR: #365 

**Add some missing functionality:**
- [x] #14 add conical volume bounds (new functionality), PR: #200 
  - conical volume bounds are needed for `Belle-2` description 

**R&D:**
- [ ] Investigate if fully local bounds memory and transform memory is CPU superior
  - currently, volume bounds are shared object that can be shared between volumes, however this could potentially lead to memory cache misses, investigate if a by value model is better in terms of CPU performance

**Add Documenation:**
- [ ] Documentation for surface module
- [ ] Documenation for geometry module

**New DetectorVolume infrastructure:** 
- [ ] #13 remove layers and describe them as volumes (improvement)
 - layers have become very close to volume objects, but have a different navigation, this can be streamlined
- [ ] Implement a new `Tracer` instead of the `Navigator` for the new `DetectorVolume` type
 - omitting layers as objects reduces the complexity of the navigation to volumes and contained surfaces, hence should result in a way more comprehensive navigation structure
- [ ] Make the new `DetectorVolume` infrastructure `const correct`
  - internally, the `DetectorVolume` infrastructure should have `non-const` objects that allow for interlinking and comprehensive handling during construction time
 - public access should be only via `const access(..) const`
- [ ] use `GeometryContext` consistently throughout the new `DetectorVolume` infrastructure
  - currently this is only supported for `Surface` instances that are connected to `DetectorElementBase`
- [ ] Implement the ATLAS muons system with stations and inert material

**Conclusion:**
- [ ]  deprecate the `TrackingGeometry` infrastructure.

**Comment by asalzburger** [comment]
Re-opening as this closed after merging the one of the PRs.
