### ISSUE TITLE
Workpackage: Implement KF-based alignment algorithm

### ISSUE THREAD

**Issue by XiaocongAi** [acts-project/acts#202]
Compared to least-squares estimator which usually requires expensive matrix computation and sometimes has to handle the material effects and magnetic field in a simplified track model, the KalmanFilter is less computationally expensive, and more importantly has an easy treatment of the material effects and particle transport in magnetic field. 

Thus, compared to the alignment based on least-squares, the KF-based alignment could allow for a more precise track model, i.e.  the same track model used for track reconstruction and physics analysis, to be used for alignment. Furthermore, for a non-linear minimization problem, the procedure usually has to be repeated iteratively to be converged. All of this could be benefited from the `Acts::KalmanFitter` with validated precision and speed performance. 

This is the epic description of implementing a KF-based alignment approach for the chi2 minimization problem:
![image](https://user-images.githubusercontent.com/30073719/82959559-d9f1ac80-9f6c-11ea-81d4-0bb76ec2fc65.png)
based on the tested [LHCb implementation](https://iopscience.iop.org/article/10.1088/1742-6596/219/3/032028/pdf).

**Add some missing functionality:**
- [x] Extend the `KalmanFitter` class to calculate the global covariance matrix (`C`), i.e. the covariance matrix for all parameters from a Kalman filter track fit (#125 ):
![image](https://user-images.githubusercontent.com/30073719/82960480-7ddc5780-9f6f-11ea-92e5-2a7ca5b8b6ed.png) `A` in this formula here means the Kalman smoothing gain matrix.
This global covariance matrix `C` is necessary for a global chi2 minimization approach where correlation between surfaces is taken into account.
- [x] Add the enum for alignment parameters (six parameters for translation + rotation) (#125)

- [x] Extend the `Surface` class to calculate the derivative of track model represented with bound track parameters w.r.t. the alignment parameters of its reference surface (#125). 
This is necessary for calculating the derivative matrix `A`.

- [ ] Extend the `Surface` to calculate the derivative of bound track parameters w.r.t. the alignment parameters of the associated layer&volume of its reference surface (similar as above)

- [ ] Add an `AlignmentEngine` to calculate the first and second derivative of minimization chi2 w.r.t. alignment parameters (size: Dof * Dof) for a single track:
![image](https://user-images.githubusercontent.com/30073719/82951725-942ce800-9f5c-11ea-821f-e16a20d207fe.png)
NB: For a single track, only part of alignment parameters are involved, i.e. it only contributes to a few elements of the whole matrix for chi2 derivatives.

**New KF-based alignment algorithm prototype implementation**

- [ ] Write an algorithm with the interface that takes a collection of trajectories, perform the fit for all trajectories, calculate the contribution of all tracks to the first and second derivative of minimization chi2 w.r.t. alignment parameters, and get the change of alignment parameters. Applying the procedure iteratively until a certain convergence criterion is met.
![image](https://user-images.githubusercontent.com/30073719/82957161-3a7deb00-9f67-11ea-9db3-b29291f46225.png)

*R&D*
- [ ] Investigate how to design the interface to allow for alignment at different granularity (i.e. alignment at volume/layer/sensitive level) and different locality (i.e. alignment for selected volume/layer/sensitive).  
For instance, the alignment Dofs for ATLAS PIX + SCT at various levels:
- Level 1: 24 Dofs
PIX: complete detector
SCT: 1 barrel + 2 end caps
- Level 2: 186 Dofs
PIX:  3 B layers + 2x3 EC disks
SCT: 4 B layers + 2x9 EC disks
- Level 3: 34992 Dofs
PIX: (B) 1456 + (EC) 2x144
SCT: (B) 2112 + (EC) 2x988

- [ ] Investigate how to store the aligned parameters

**Algorithm validation**

- [ ] Test with a `CubicTrackingGeometry` with very limited detector alignment Dofs (There are 6 planes for this geometry, so there are at most 6 * 6 = 36 Dofs)
- [ ] Test with the `GenericDetector` geometry with much more alignment Dofs

*R&D*
- [ ] How to get truth trajectories with misaligned detector geometry (probably with the `AlignmentDecorator`)

**Add Documentation**
- [ ] Documentation for the various covariance and derivative calculation

**Long-long-term R&D**
- [ ] Weak mode (Curl, Twist, Telescope, Elliptical)
- [ ] Speed-up dense matrix operation with GPUs (could fit well into the data-level parallelism with GPUs)

**Comment by paulgessinger** [comment]
@msmk0 this has been closed twice now. Nothing has happened for over 2 months. What is the point of having this issue open if nothing is being done here?

**Comment by msmk0** [comment]
You might be right. There was work ongoing in #100. @XiaocongAi what is the actual status? Should we leave this open or close it for now?

**Comment by XiaocongAi** [comment]
Sorry, I'm busy with the GPU staff and have not updated this for a while. But yes, it's to be updated. So it'll be great if we could leave it open for now.

**Comment by HadrienG2** [comment]
I guess it fundamentally boils down to what the role of code repository issues are. Do you use them to track down an exhaustive list of problems with the code that should be resolved at some point, or to track down the much smaller list of stuff that is actively being worked on ?

**Comment by XiaocongAi** [comment]
@HadrienG2 , that's a good question. This issue is used a track an exhaustive list of problems which might still need to investigated. In that sense, it might make more sense to close it for now?

**Comment by paulgessinger** [comment]
That's totally debatable. I personally think a long list of issues where half are abandoned is not useful. I'm happy to reopen anything if there is activity, even if it's just discussion.

**Comment by XiaocongAi** [comment]
@paulgessinger , that makes sense! Let's close it now and open more dedicated ones when necessary.
