### ISSUE TITLE
Switch to monorepo

### ISSUE THREAD

**Issue by paulgessinger** [acts-project/acts#22]
[GitLab issue: #686](https://gitlab.cern.ch/acts/acts-core/issues/686)

Our current practice of splitting components over multiple repositories, e.g. Core, Fatras, Framework, has lead to undiscovered breakage and impedance missmatch during development. E.g. changes in the Core lead to performance regressions that were discovered only much later in the framework. Git submodule handling is also hard to understand, especially for beginners, and breaks easily.

Switching to a monorepo with optional build components should allow consistent development and testing without the current delay between Core and Framework. Optional component handling is already available in the Core and can be easily reused for this.

At the end, the directory structure of the merged repository should look as follows:

```shell
# as-before
Core/
  include/
    ...
  src/
    ...
# as-before (could also be renamed to CorePlugins to clarify the relation to Core)
Plugins/
  DD4hep/
    ...
  # previously handle as special, but can be treated as just another plugin
  Legacy/
    ...
  ...
# cleaned-up content from acts-fatras/Core
Fatras/
  include/
    ...
  src/
    ...
# cleaned-up content from acts-framework
Standalone/
  Algorithms/
    ...
  Detectors/
    ...
  Framework/
    ...
  Io/
    ...
  # formerly 'Examples'
  Run/
    ...
Tests/
  Benchmarks/
    ...
  Examples/
    ...
  # integration tests, can use multiple components
  IntegrationTests/
    ...
  # unit-tests, should always use only a single component
  UnitTests/
    Core/
      ...
    Plugins/
      ...
    Fatras/
      ...
    Framework/
      ...
# as-before
docs/
  ...
# 3rd party libraries that are usually not available via the system
# package manager; shipped as copies and built as part of the regular
# process. use copies instead of submodules to avoid the headache.
# keep this limited to small libraries/ few files by policy.
thirdparty/
  dfelibs/
    ...
  nlohmann_json/
    ...
```

Target names can use the current style to provide a bit of namespacing, i.e.

```
# core
ActsCore
# core plugins
# TODO this should be named ActsPlugin... for consistency
Acts...Plugin
# fatras
ActsFatras
# Standalone framework components
ActsStandalone...
# Standalone chains (formerly part of acts-framework)
ActsExample...
ActsGen...
ActsSim...
ActsRec...
# tests
ActsBenchmark...
ActsIntegrationTest...
ActsUnitTest...
```

This is a major change and will and should not happen at once, i.e. within one of the current weekly/biweekly release cycle. There is also some clean-up in progress for both Fatras and the Framework. This should finish before moving the code back to the main repository.

Propose schedule/ order:

* [x] Prepare main repository
    * [x] Verify CMake tools are sufficient (Existing tools `ActsComponentsHelpers.cmake` can be used directly for additional components)
    * [x] Make `Legacy` a regular plugin (#688, !750)
    * [x] Split integration and unit tests (#689, !749)
    * [x] Move nlohman json library to `thirdparty` (!733)
    * [ ] ~~Rename plugin targets to `ActsPlugin...`~~ (not for now)
* [x] Add Gitlab labels to tag issues for specific components (Available as group labels `Component - ...`)
* [x] ~~Finish Fatras clean-up~~ Clean up Fatras after import into Core repo
    * [x] ~~acts-fatras#1~~ now tracked as #693
    * [x] acts-fatras#2
    * [x] ~~acts-fatras#3~~ now tracked as #694 
    * [x] ~~acts-fatras#4~~ now tracked as #695 
    * [x] ~~acts-fatras#5~~ now tracked as #696 
    * [x] ~~acts-fatras#6~~ now tracked as #697 
    * [x] ~~acts-fatras#7~~ now tracked as #698 
* [x] Move Fatras component to main repo (!751)
* [ ] ~~Finish Framework clean-up~~ Clean up after import
    * [ ] ~~acts-framework#162~~
    * [ ] ~~acts-framework#163~~
    * [ ] ~~acts-framework#164~~
    * [ ] ~~acts-framework#165~~
    * [ ] ~~acts-framework#167~~
    * [ ] ~~acts-framework#174~~
    * [ ] ~~acts-framework#175~~
    * [ ] ~~acts-framework#182~~
* [ ] Move Framework components to main repo
