### ISSUE TITLE
The laundry list (a.k.a Workpackage: Cleanup)

### ISSUE THREAD

**Issue by msmk0** [acts-project/acts#221]
This is a tracking issue for various cleanup plans. All changes do not affect any functionality but aim to provide a more consistent code base.

## Core

The following items need a discussion/decision

- [x] Use consistent track parameter type names #151
- [x] Fix axis enum for space points/ remove separate SpacePoint type #143
- [x] Remove global track state information from bound parameters #35
- [ ] ~~Towards a configurable underlying float type #156~~

While these items just need someone to start

- [x] Remove obsolete parameter enums #137
- [x] Apply naming conventions consistently.
- [x] Replace `eLOC_0` et al. enum values with correct ones #190
- [x] Rename the concepts namespace #42
- [x] Clean up the version header #28
- [x] Fix misleading material class names #29

## Fatras

- [x] Move `Interactor` to the detail namespace #11 

## Examples

- [x] Use `ActsExamples` namespace and update include hierarchy #130
- [x] Use flat event data model #154
- [ ] Split event generation and simulation tools #134
- [x] Use `std::filesystem` instead of `boost::filesystem` #193
