### ISSUE TITLE
Missing tracking geometry

### ISSUE THREAD

**Issue by whit2333** [acts-project/acts#860]
The endcaps are missing from the tracking geometry when I look at the output in cad (via obj writing).

![image](https://user-images.githubusercontent.com/2065918/123480015-5bc86500-d5c7-11eb-8757-9f51c0f0bf28.png)

Here is the full geometry: 
https://eic.phy.anl.gov/geoviewer/index.htm?nobrowser&file=https://eicweb.phy.anl.gov/api/v4/projects/473/jobs/artifacts/master/raw/geo/detector_geo.root?job=report&item=default;1&opt=clipxyz;transp30;zoom100;ROTY0;ROTZ0;trz100;trr0;ctrl;all&

The verbose dd4hep plugin output: https://eicweb.phy.anl.gov/EIC/detectors/athena/-/jobs/134537
Everything seems to run OK.

**Comment by paulgessinger** [comment]
Looks to me like it picks up on the endcap volumes at least since the log ends with
```
 { TOFSubAssembly::NegativeEndcap | { { TOFSubAssembly::fGap | { { TrackerSubAssembly_Outer::fGap | { TrackerSubAssembly_Inner::NegativeEndcap | { { TrackerSubAssembly_Inner::fGap | { VertexEndcapSubAssembly::NegativeEndcap | { VertexEndcapSubAssembly::fGap | VertexBarrelSubAssembly::Barrel | VertexEndcapSubAssembly::sGap } | VertexEndcapSubAssembly::PositiveEndcap } | TrackerSubAssembly_Inner::sGap } | TrackerSubAssembly_Inner::Barrel } | TrackerSubAssembly_Inner::PositiveEndcap } | TrackerSubAssembly_Outer::sGap } | { TrackerSubAssembly_Outer::NegativeEndcap | TrackerSubAssembly_Outer::Barrel | TrackerSubAssembly_Outer::PositiveEndcap } } | TOFSubAssembly::sGap } | TOFSubAssembly::Barrel } | TOFSubAssembly::PositiveEndcap }
```

Maybe it's not adding the sensors inside these volumes? The log says 

```
15:34:24    D2A_L:Vertex   VERBOSE    Disc layer has no sensitive surfaces.
```

a number of times, though off the top of my head, I wouldn't know why that would happen.

Any idea @asalzburger ?

**Comment by asalzburger** [comment]
Hi, apologies - I did not have time to start investigating this yet.

Indeed, what @paulgessinger is pointing out is worrisome, if there are no senstive surfaces found, then they will not appear here. I will try to reproduce this in the next days.

**Comment by asalzburger** [comment]
This could be a missing `ActsExtension`

**Comment by whit2333** [comment]
@asalzburger  you can see the implementation here:
https://eicweb.phy.anl.gov/EIC/detectors/athena/-/blob/master/src/TrapEndcapTracker_geo.cpp#L197

**Comment by whit2333** [comment]
@asalzburger and @paulgessinger, do you have any idea what happened to the endcaps?

**Comment by whit2333** [comment]
I found the reason why the endcaps were missing. The module DD4hep::DetElement's parent was not the layer DetElement (ie it was a sibling to the layer). Changing this, I found some other issues which were fixed. 
See here for details: https://eicweb.phy.anl.gov/EIC/detectors/athena/-/merge_requests/88

Now the only question is why I have to separate the barrel/endcap sub-assemblies (eg the vertex barrel/endcaps) but this is only minor. Ultimately there is probably a cleaner way to implement the plugin that doesn't presume a certain geometry layout.

**Comment by asalzburger** [comment]
Thanks @whit2333 - I had a chat with the `DD4hep` and I think we have to do some cleanup of this module.


Here's a few things:
- [ ] currently if you want to use ACTS with DD4Hep - your factories become dependent on ACTS, this should/will be solved by running the ACTS decoration as a DD4hep plugin
- [ ] there's still quite some assumption on how a geometry can look like for the parser to understand it, I *think* this should not be the case, and I have a few ideas how to get around this one
- [ ] ideally, though, this should come after my summer work package, which is to abandon the Layer class and only have volumes and surfaces

**Comment by whit2333** [comment]
@asalzburger, thanks for the info. This all sounds great!

I have a question/comments about the first item:
Do you plan on implementing what looks to be called a dd4hep "surface installer plugin"? I would suggest that ACTS take advantage of the dd4hep surfaces which can explicitly define a coordinate system (u,v,n) in the detector construction. The third item in your list would put dd4hep and acts at nearly the same level of tracking geometry description, and in theory, should help in resolving your second item.

**Comment by whit2333** [comment]
@asalzburger,
To follow up with the problem we are having: https://eicweb.phy.anl.gov/EIC/detectors/athena/-/issues/50 

The first of the errors there look [like this:](https://eicweb.phy.anl.gov/EIC/detectors/athena/-/jobs/152248#L1500)
```
...
20:38:50    D2A_CVH        VERBOSE      -> volume 'TrackerBarrelSubAssembly_Outer::fGap
20:38:50    D2A_CVH        VERBOSE      -> volume 'TrackerEndcapSubAssembly_Inner::NegativeEndcap
20:38:50    D2A_CVH        VERBOSE      -> volume 'TrackerEndcapSubAssembly_Inner::sGap
20:38:50    D2A_CVH        VERBOSE      -> volume 'TrackerEndcapSubAssembly_Inner::PositiveEndcap
20:38:50    D2A_CVH        VERBOSE   [ end ] return newly created container : { TrackerBarrelSubAssembly_Outer::fGap | { { { { TrackerBarrelSubAssembly_Inner::fGap | { { VertexEndcapSubAssembly::fGap | VertexBarrelSubAssembly::Barrel | VertexEndcapSubAssembly::sGap } | { VertexEndcapSubAssembly::NegativeEndcap | VertexEndcapSubAssembly::PositiveEndcap } } } | TrackerBarrelSubAssembly_Inner::Barrel } | TrackerEndcapSubAssembly_Inner::sGap } | { TrackerEndcapSubAssembly_Inner::NegativeEndcap | TrackerEndcapSubAssembly_Inner::PositiveEndcap } } }
20:38:50    D2A_V:Tracke   ERROR     Misconfiguration in volume building detected.
20:38:50    D2A_V:Tracke   DEBUG     Configured to build volume : TrackerEndcapSubAssembly_Outer
20:38:50    D2A_L:Tracke   VERBOSE    Received layers for negative volume -> creating disc layers
20:38:50    D2A_L:Tracke   VERBOSE    Disc layer has 12 senstive surfaces.
20:38:50    D2A_LAC        VERBOSE   Creating a disk Layer:
20:38:50    D2A_LAC        VERBOSE    - at Z position    = -686.667
20:38:50    D2A_LAC        VERBOSE    - from Z min/max   = -689.276 / -684.261
20:38:50    D2A_LAC        VERBOSE    - with Z thickness = 233.333
20:38:50    D2A_LAC        VERBOSE      - incl envelope  = 114.057 / 114.261
20:38:50    D2A_LAC        VERBOSE    - with R min/max   = 31.8 (-1.77636e-14) / 432.3 (+5.68434e-14)
20:38:50    D2A_LAC        VERBOSE    - with phi min/max = -2.88833 / 2.88833
20:38:50    D2A_LAC        VERBOSE    - # of modules     = 12
20:38:50    D2A_SAC        VERBOSE   Creating a SurfaceArray on a disc
20:38:50    D2A_SAC        VERBOSE   Create equidistant binning Axis for binned SurfaceArray
20:38:50    D2A_SAC        VERBOSE   	BinningValue: 3
20:38:50    D2A_SAC        VERBOSE   	(binX = 0, binY = 1, binZ = 2, binR = 3, binPhi = 4, binRPhi = 5, binH = 6, binEta = 7)
20:38:50    D2A_SAC        VERBOSE   	Number of bins: 1
20:38:50    D2A_SAC        VERBOSE   	(Min/Max) = (31.8/432.3)
20:38:50    D2A_SAC        VERBOSE   Create equidistant binning Axis for binned SurfaceArray
20:38:50    D2A_SAC        VERBOSE   	BinningValue: 4
20:38:50    D2A_SAC        VERBOSE   	(binX = 0, binY = 1, binZ = 2, binR = 3, binPhi = 4, binRPhi = 5, binH = 6, binEta = 7)
20:38:50    D2A_SAC        VERBOSE   	Number of bins: 12
20:38:50    D2A_SAC        VERBOSE   	(Min/Max) = (-3.14159/3.14159)
20:38:50    D2A_SAC        VERBOSE   - z-position of disk estimated as -686.667
20:38:50    D2A_SAC        VERBOSE    -- with 12 surfaces.
20:38:50    D2A_SAC        VERBOSE    -- with r x phi  = 1 x 12 = 12 bins.
20:38:50    D2A_SAC        VERBOSE   Complete binning by filling closest neighbour surfaces into empty bins.
20:38:50    D2A_SAC        VERBOSE          filled  : 0 (includes under/overflow)
20:38:50    D2A_LAC        VERBOSE   Performing consistency check
20:38:50    D2A_LAC        VERBOSE    - Checked 12 valid bins
20:38:50    D2A_LAC        VERBOSE    -- All bins point to a surface
20:38:50    D2A_LAC        VERBOSE    -- All sensitive surfaces are accessible through binning.
20:38:50    D2A_L:Tracke   VERBOSE    Disc layer has 12 senstive surfaces.
20:38:50    D2A_LAC        VERBOSE   Creating a disk Layer:
20:38:50    D2A_LAC        VERBOSE    - at Z position    = -920
20:38:50    D2A_LAC        VERBOSE    - from Z min/max   = -922.61 / -917.595
20:38:50    D2A_LAC        VERBOSE    - with Z thickness = 233.333
20:38:50    D2A_LAC        VERBOSE      - incl envelope  = 114.057 / 114.261
20:38:50    D2A_LAC        VERBOSE    - with R min/max   = 43.8 (-3.55271e-14) / 432.3 (+0)
20:38:50    D2A_LAC        VERBOSE    - with phi min/max = -2.88833 / 2.88833
20:38:50    D2A_LAC        VERBOSE    - # of modules     = 12
20:38:50    D2A_SAC        VERBOSE   Creating a SurfaceArray on a disc
20:38:50    D2A_SAC        VERBOSE   Create equidistant binning Axis for binned SurfaceArray
20:38:50    D2A_SAC        VERBOSE   	BinningValue: 3
20:38:50    D2A_SAC        VERBOSE   	(binX = 0, binY = 1, binZ = 2, binR = 3, binPhi = 4, binRPhi = 5, binH = 6, binEta = 7)
20:38:50    D2A_SAC        VERBOSE   	Number of bins: 1
20:38:50    D2A_SAC        VERBOSE   	(Min/Max) = (43.8/432.3)
20:38:50    D2A_SAC        VERBOSE   Create equidistant binning Axis for binned SurfaceArray
20:38:50    D2A_SAC        VERBOSE   	BinningValue: 4
20:38:50    D2A_SAC        VERBOSE   	(binX = 0, binY = 1, binZ = 2, binR = 3, binPhi = 4, binRPhi = 5, binH = 6, binEta = 7)
20:38:50    D2A_SAC        VERBOSE   	Number of bins: 12
20:38:50    D2A_SAC        VERBOSE   	(Min/Max) = (-3.14159/3.14159)
20:38:50    D2A_SAC        VERBOSE   - z-position of disk estimated as -920
20:38:50    D2A_SAC        VERBOSE    -- with 12 surfaces.
20:38:50    D2A_SAC        VERBOSE    -- with r x phi  = 1 x 12 = 12 bins.
20:38:50    D2A_SAC        VERBOSE   Complete binning by filling closest neighbour surfaces into empty bins.
20:38:50    D2A_SAC        VERBOSE          filled  : 0 (includes under/overflow)
20:38:50    D2A_LAC        VERBOSE   Performing consistency check
20:38:50    D2A_LAC        VERBOSE    - Checked 12 valid bins
20:38:50    D2A_LAC        VERBOSE    -- All bins point to a surface
20:38:50    D2A_LAC        VERBOSE    -- All sensitive surfaces are accessible through binning.
20:38:50    D2A_L:Tracke   VERBOSE    Disc layer has 12 senstive surfaces.
20:38:50    D2A_LAC        VERBOSE   Creating a disk Layer:
20:38:50    D2A_LAC        VERBOSE    - at Z position    = -1153.33
20:38:50    D2A_LAC        VERBOSE    - from Z min/max   = -1155.94 / -1150.93
20:38:50    D2A_LAC        VERBOSE    - with Z thickness = 233.333
20:38:50    D2A_LAC        VERBOSE      - incl envelope  = 114.057 / 114.261
20:38:50    D2A_LAC        VERBOSE    - with R min/max   = 55.8 (-7.10543e-15) / 432.3 (+1.13687e-13)
20:38:50    D2A_LAC        VERBOSE    - with phi min/max = -2.88833 / 2.88833
...
```

After this [we get the error](https://eicweb.phy.anl.gov/EIC/detectors/athena/-/jobs/152248#L1703):
```
20:38:50    D2A_LAC        ERROR     Layers are overlapping at: -1036.67. This should never happen. Please check your geometry description.
```

**Comment by whit2333** [comment]
OK. I found the cause: the endcap layer surfaces were overlapping.  @asalzburger, Is this the layer concept that will be removed in the future?

**Comment by whit2333** [comment]
I will close the issue since I think it is fixed now.
